version: '2'
services:
  httpd:
    container_name: tryecscli-httpd
    hostname: zuckscojp-httpd
    image: 825814182855.dkr.ecr.ap-northeast-1.amazonaws.com/tryecscli-httpd
    ports:
      - 80:80
      - 443:443
    networks:
      - network-tryecscli
    volumes:
      - $PWD:/web/try-ecs-cli

  php:
    container_name: tryecscli-php
    hostname: tryecscli-php
    image: 825814182855.dkr.ecr.ap-northeast-1.amazonaws.com/tryecscli-php
    expose:
      - 9000
    networks:
      - network-tryecscli
    volumes:
      - $PWD:/web/try-ecs-cli

networks:
  network-tryecscli:
