version: '2'
services:
  httpd:
    image: tryecscli/httpd
    build: ./docker/httpd
    ports:
      - 8080:80
      - 443:443
    networks:
      - network-tryecscli
    volumes:
      - $PWD:/web/try-ecs-cli

  php:
    image: tryecscli/php
    build: ./docker/php
    expose:
      - 9000
    networks:
      - network-tryecscli
    volumes:
      - $PWD:/web/try-ecs-cli

networks:
  network-tryecscli:
